tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "wix/brew"
cask_args appdir: "/Applications"

brew "applesimutils"
brew "gpg"
brew "grep"
brew "ios-deploy"
brew "lf"
brew "mas"
brew "rbenv"
brew "starship"
brew "stow"
brew "tmux"
brew "watchman"
brew "yarn"
brew "zsh"

cask "ableton-live-suite9"
cask "adobe-creative-cloud"
cask "adoptopenjdk/openjdk/adoptopenjdk8"
cask "alacritty"
cask "amethyst"
cask "android-studio"
cask "brave-browser"
cask "figma"
cask "flipper"
cask "google-japanese-ime"
cask "homebrew/cask-versions/visual-studio-code-insiders"
cask "minecraft"
cask "obs"
cask "slack"
cask "soundflower"

mas "Xcode", id: 497799835
