# Base16 Material Palenight 256 - alacritty color config
# Nate Peterson
shell:
  program: /bin/bash
  args:
    - --login

colors:
  # Default colors
  primary:
    background: '0x292d3e'
    foreground: '0x959dcb'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x292d3e'
    cursor: '0x959dcb'

  # Normal colors
  normal:
    black:   '0x292d3e'
    red:     '0xf07178'
    green:   '0xc3e88d'
    yellow:  '0xffcb6b'
    blue:    '0x82aaff'
    magenta: '0xc792ea'
    cyan:    '0x89ddff'
    white:   '0x959dcb'

  # Bright colors
  bright:
    black:   '0x676e95'
    red:     '0xf07178'
    green:   '0xc3e88d'
    yellow:  '0xffcb6b'
    blue:    '0x82aaff'
    magenta: '0xc792ea'
    cyan:    '0x89ddff'
    white:   '0xffffff'

  indexed_colors:
    - { index: 16, color: '0xf78c6c' }
    - { index: 17, color: '0xff5370' }
    - { index: 18, color: '0x444267' }
    - { index: 19, color: '0x32374d' }
    - { index: 20, color: '0x8796b0' }
    - { index: 21, color: '0x959dcb' }

font:
  # The normal (roman) font face to use.
  normal:
    family: Roboto Mono for Powerline # should be "Menlo" or something on macOS.
    # Style can be specified to pick a specific face.
    # style: Regular

  # The bold font face
  bold:
    family: Roboto Mono for Powerline # should be "Menlo" or something on macOS.
    # Style can be specified to pick a specific face.
    #style: Bold

  # The italic font face
  italic:
    family: Roboto Mono for Powerline # should be "Menlo" or something on macOS.
    # Style can be specified to pick a specific face.
    # style: Italic
  size: 16
background_opacity: 0.95
